### ISSUE TITLE
TODO Add reponse of the devslopes book

### ISSUE THREAD

**Issue by Kiri23** [devslopes/discord-bot#20]
Condition1 = When the book is coming out.
Condition2 = When the devslopes book is coming out.

Response = The deadline for the book is November 30th. This is not a release date but it's when we will send the book off to the Kindle/iBooks store and also to the book printer

Add this Conditions to the if Statements and in the body add the response with message.reply(Response)
e.g
if (condition || condition2) {
message.reply(Response)
)

**Comment by cassidycr94** [comment]
Done
