### ISSUE TITLE
TODO Add Response 

### ISSUE THREAD

**Issue by Kiri23** [devslopes/discord-bot#7]
Condition1 = Hi I can still get the <b>--devslopes--</b> <b>--iOS--</b>  <b>--Kickstarter--</b> book  . 
Condition2 = where I can buy the <b>--devslopes--</b>  book. 
Response = "Yes you can buy the book email jason@devslope.com"

Add this Conditions to the `if Statements` and in the body add the response with <code>message.reply(Response)</code> 
e.g 
`if (condition 1 || condition2) { `
   `message.reply(Response)`
`)`

**Comment by cassidycr94** [comment]
Done
